### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by Foundsheep** [juraam/stable-diffusion-from-scratch#2]
Hi, I admire your efforts put in this repo, and I've arrived here while I was trying to find a source that explains how a latent diffusion model could be trained.

My question is, isn't this model just a DDPM, not a stable diffusion which requires of vae somewhere in the training?

**Comment by juraam** [comment]
Thank you for question, current repository explains original DDPM and Conditional DDPM models, it doesn't work in latent space, you are right.
